version: "3"

services:
  mongo_db:
    container_name: mongo_db
    ports:
      - 8001:27017
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  app:
    build: .
    ports:
      - 5001:3000
    environment:
      APP_NAME: NodeServer
      PORT: 3000
      DB_URI: mongodb://mongo_db:27017/docker
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
