db = db.getSiblingDB("docker");

db.clients.insertMany([
  {
    username: "client",
    email: "client@email.com",
    fullname: "Client",
    client_type: "Technical",
    password: "$2a$10$0I9kCnsc8PKycuImPcEfHO3P5CbSLUjOZVyKFbEoyvq9YnH9SlyRq",
    country: "Singapore",
    role: "client",
    workshop: [],
  },
  {
    username: "johndoefromjohnbrosinc",
    email: "johndoefromjohnbrosinc@email.com",
    fullname: "johndoefromjohnbrosinc",
    client_type: "Executive",
    password: "$2a$10$tb.sifvCVRC3yJdRt0TGgeCwT42R9T7AMOuXIvllEXcmr1ZJ../Qi",
    country: "Singapore",
    role: "client",
    workshop: [],
  },
]);

db.trainers.insertMany([
  {
    username: "trainer",
    email: "trainer@email.com",
    fullname: "trainer",
    password: "$2a$10$.dhERvM2156v1O9.6iqwZOY9lUyROAQE0JtyHaO7cjuj3.hrunGNe",
    role: "trainer",
    availability: "Active",
    trainer_role: "Trainer Lead",
    workshops_completed_this_month: 0,
    ongoing_workshops: 0,
    workshops_completed_total: 0,
    workshop_request: [],
    unavailableTimeslots: [],
  },
  {
    username: "Trainer_3_JohnDoe",
    email: "Trainer_3_JohnDoe@email.com",
    fullname: "Trainer_3_JohnDoe",
    password: "$2a$10$ch9V9/itSbDYVALT9Xl21eIMMfFBdMHNClSIYREZ1FmvtnO9Fhrg.",
    role: "trainer",
    availability: "Active",
    trainer_role: "Trainer Lead",
    workshops_completed_this_month: 0,
    ongoing_workshops: 0,
    workshops_completed_total: 0,
    workshop_request: [],
    unavailableTimeslots: [],
  },
]);

console.log("here123");

db.workshopdatas.insertMany([
  {
    workshop_name: "Intro to Python",
    workshop_ID: "01",
    workshop_type: "Business Value Discovery",
    workshop_details: "Nothing to do with the snake.",
    availability: "Available",
    workshop_requests: [],
  },
  {
    workshop_name: "Intro to Java 21",
    workshop_ID: "02",
    workshop_type: "Business Value Discovery",
    workshop_details: "No its not about Indonesia.",
    availability: "Available",
    workshop_requests: [],
  },
  {
    workshop_name: "Intro to AI",
    workshop_ID: "03",
    workshop_type: "AI Platform",
    workshop_details: "hello world!",
    availability: "Available",
    workshop_requests: [],
  },
  {
    workshop_name: "Intro to C Hashtag",
    workshop_ID: "04",
    workshop_type: "Infrastructure and Demo",
    workshop_details:
      "Those saying its C sharp don't know what they're talking about...",
    availability: "Available",
    workshop_requests: [],
  },
]);
//// generating variables for workshop requests
const clientJohnDoe = db.clients.findOne({
  username: "johndoefromjohnbrosinc",
});
const clientClient = db.clients.findOne({ username: "client" });

const workshopData1 = db.workshopdatas.findOne({
  workshop_name: "Intro to Python",
});
const workshopData2 = db.workshopdatas.findOne({
  workshop_name: "Intro to Java 21",
});
const workshopData3 = db.workshopdatas.findOne({
  workshop_name: "Intro to AI",
});

console.log("client:", clientJohnDoe);
console.log("workshopData1:", workshopData1);
console.log("workshopData2:", workshopData2);
console.log("workshopData3:", workshopData3);

const trainer1 = db.trainers.findOne({
  username: "trainer",
});
const trainer2 = db.trainers.findOne({
  username: "Trainer_3_JohnDoe",
});

console.log("trainer1:", trainer1._id);
console.log("trainer2:", trainer2._id);

//// inserting workshop requests
db.workshoprequests.insertMany([
  {
    company_role: "Manager",
    company: "Company A",
    name: "John Doe",
    email: "john.doe@companya.com",
    phone_number: 1234567890,
    pax: 20,
    deal_potential: 5000,
    country: "USA",
    venue: "Venue A",
    start_date: new Date("2024-07-01"),
    end_date: new Date("2024-07-02"),
    request_message: "Looking forward to this workshop",
    status: "submitted",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData2._id,
    trainers: [],
    client: clientJohnDoe._id,
  },
  {
    company_role: "Director",
    company: "Company B",
    name: "Jane Smith",
    email: "jane.smith@companyb.com",
    phone_number: 2345678901,
    pax: 30,
    deal_potential: 10000,
    country: "Singapore",
    venue: "Venue B",
    start_date: new Date("2024-07-05"),
    end_date: new Date("2024-07-06"),
    request_message: "Please provide details",
    status: "submitted",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData1._id,
    trainers: [],
    client: clientJohnDoe._id,
  },
  {
    company_role: "Team Lead",
    company: "Company C",
    name: "Alice Johnson",
    email: "alice.johnson@companyc.com",
    phone_number: 3456789012,
    pax: 15,
    deal_potential: 7000,
    country: "Singapore",
    venue: "Venue C",
    start_date: new Date("2024-07-27"),
    end_date: new Date("2024-07-30"),
    request_message: "Excited about this workshop",
    status: "submitted",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData3._id,
    trainers: [],
    client: clientJohnDoe._id,
  },
  {
    company_role: "CTO",
    company: "Company D",
    name: "Bob Brown",
    email: "bob.brown@companyd.com",
    phone_number: 4567890123,
    pax: 25,
    deal_potential: 12000,
    country: "Australia",
    venue: "Venue D",
    start_date: new Date("2023-08-15"),
    end_date: new Date("2023-08-16"),
    request_message: "Looking for detailed insights",
    status: "approved",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData3._id,
    trainers: [trainer1._id],
    client: clientJohnDoe._id,
  },
  {
    company_role: "CEO",
    company: "Company E",
    name: "Charlie Davis",
    email: "charlie.davis@companye.com",
    phone_number: 5678901234,
    pax: 10,
    deal_potential: 3000,
    country: "Malaysia",
    venue: "Venue E",
    start_date: new Date("2023-08-20"),
    end_date: new Date("2023-08-21"),
    request_message: "Need advanced strategies",
    status: "approved",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData2._id,
    trainers: [trainer1._id],
    client: clientJohnDoe._id,
  },
  {
    company_role: "Project Manager",
    company: "Company F",
    name: "David Evans",
    email: "david.evans@companyf.com",
    phone_number: 6789012345,
    pax: 18,
    deal_potential: 8000,
    country: "Malaysia",
    venue: "Venue F",
    start_date: new Date("2023-02-25"),
    end_date: new Date("2023-02-26"),
    request_message: "Excited for this opportunity",
    status: "approved",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData1._id,
    trainers: [trainer2._id, trainer1._id],
    client: clientJohnDoe._id,
  },
  {
    company_role: "HR Manager",
    company: "Company G",
    name: "Eva Green",
    email: "eva.green@companyg.com",
    phone_number: 7890123456,
    pax: 22,
    deal_potential: 6000,
    country: "Singapore",
    venue: "Venue G",
    start_date: new Date("2023-03-30"),
    end_date: new Date("2023-03-31"),
    request_message: "Looking for HR solutions",
    status: "approved",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData2._id,
    trainers: [trainer2._id],
    client: clientClient._id,
  },
  {
    company_role: "Marketing Head",
    company: "Company H",
    name: "George Hill",
    email: "george.hill@companyh.com",
    phone_number: 8901234567,
    pax: 28,
    deal_potential: 9000,
    country: "USA",
    venue: "Venue H",
    start_date: new Date("2023-09-05"),
    end_date: new Date("2023-09-06"),
    request_message: "Need marketing strategies",
    status: "approved",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData3._id,
    trainers: [trainer1._id],
    client: clientClient._id,
  },
  {
    company_role: "Sales Manager",
    company: "Company I",
    name: "Helen Irwin",
    email: "helen.irwin@companyi.com",
    phone_number: 9012345678,
    pax: 12,
    deal_potential: 4000,
    country: "Singapore",
    venue: "Venue I",
    start_date: new Date("2023-09-10"),
    end_date: new Date("2023-09-11"),
    request_message: "Focus on sales techniques",
    status: "approved",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData2._id,
    trainers: [trainer1._id],
    client: clientClient._id,
  },
  {
    company_role: "Sales Manager",
    company: "Company J",
    name: "jelly jean",
    email: "jelly.jean@companyj.com",
    phone_number: 8046745642,
    pax: 432,
    deal_potential: 54000,
    country: "Singapore",
    venue: "Venue J",
    start_date: new Date("2024-07-28"),
    end_date: new Date("2024-07-29"),
    request_message: "jelly bean productions",
    status: "submitted",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData1._id,
    trainers: [],
    client: clientClient._id,
  },
  {
    company_role: "Sales Manager",
    company: "Company K",
    name: "kellen hellar",
    email: "kellen.hellar@companyK.com",
    phone_number: 6231235678,
    pax: 52,
    deal_potential: 90000,
    country: "Singapore",
    venue: "Venue J",
    start_date: new Date("2024-07-17"),
    end_date: new Date("2024-07-20"),
    request_message: "king fisher",
    status: "submitted",
    reject_reason: "",
    utilisation: [
      { hours: 1, utilisation_details: "Detail 1" },
      { hours: 2, utilisation_details: "Detail 2" },
      { hours: 3, utilisation_details: "Detail 3" },
      { hours: 4, utilisation_details: "Detail 4" },
    ],
    workshop_data: workshopData2._id,
    trainers: [],
    client: clientClient._id,
  },
]);
