import mongoose from "mongoose";

const trainerSchema = new mongoose.Schema({
    //AddTrainer is not yet fixed
    //id_ will be automatically generated by MongoDB
    username: { type: String, required: true, unique: true },
    email: { type: String, required: true, unique: true },
    fullname: { type: String, required: true },
    password: { type: String, required: true },
    country: { type: String, required: true },
    role: { type: String, default: "trainer" },
    availability: { type: Boolean, default: true },
    trainer_ID: { type: String, required: true, unique: true },
    trainer_role: { type: String, required: true },
    workshops_completed_this_month: { type: Number, default: 0, required: false },
    experience: { type: Number, required: true },
    gender: { type: String, required: true },
    ongoing_workshops: { type: Number, default: 0, required: false },
    workshops_completed_total: { type: Number, default: 0, required: false },
    workshops: [{ type: mongoose.Schema.Types.ObjectId, ref: "Workshop" }],
});

const TrainerModel = mongoose.model("Trainer", trainerSchema);

export { TrainerModel as Trainer };